name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

env: 
    CHANNEL_Name: InterviewPro
  

jobs:
  job1:
     runs-on: ubuntu-latest

     steps:
     - name: access secrets
       run: echo ${{secrets.GAKEY}}
     - name: access secrets
       run: echo ${{secrets.CAPTCHA}}

   

    
     
